body:
  - type: textBlock
    attributes:
      name: description
      description: >
        Choose the age, in hours, of the downloaded currency rates file before the plugin will download a new version. 
        The currency rates are updated daily and uses free API from https://github.com/fawazahmed0/currency-api
        The API provides daily updated exchange rates for various currencies including major fiat currencies.
